
<div style="text-align: center;">
  <img src="https://github.com/Hack-io-Data/Imagenes/blob/main/01-LogosHackio/logo_celeste@4x.png?raw=true" alt="esquema" />
</div>


# Laboratorio de Python: break(), pass(), continue()

## Ejercicio 1: Validación de datos numéricos. 

Escribe un bucle que lea una lista de números y detenga la ejecución si encuentra un valor negativo. Muestra un mensaje indicando el número negativo encontrado.


In [1]:
import numpy as np

In [32]:
arr = np.random.randint(-10, 100, size = 15)
print(arr)
for ele in arr:
    if ele < 0:
        print(f'Número negativo encontrado: {ele}')
        break

[76 97 32 71 61  2 63 82 53 60 -8 92 32 73 40]
Número negativo encontrado: -8



## Ejercicio 2: Filtrado de datos

Escribe un bucle que imprima los números de una lista, pero que omita los números pares.


In [35]:
arr = np.random.randint(0, 100, size = 15)
for ele in arr:
    if ele%2 != 0:
        print(ele)
    else: 
        continue

61
79
47
95
21
5
45
59
31


## Ejercicio 3: Búsqueda de un valor

Escribe un programa que busque un valor específico en una lista y detenga la búsqueda cuando lo encuentre. Si se encuentra, muestra un mensaje.


In [69]:
arr = np.random.randint(0, 100, size = 1500)
x = 101
arr[np.random.randint(0, len(arr))] = x

for i in range(len(arr)):
    if arr[i] == x:
        print(f'Elemento encontrado en posición: {i}.')
    else:
        continue

Elemento encontrado en posición: 1322.


## Ejercicio 4: Estructura de código incompleto

Define una función que aún no tenga lógica implementada, pero que se pueda ejecutar sin errores utilizando `pass`.

In [73]:
def ilogic(arr):
    sqrts = []
    for ele in arr:
        if ele < 0:
            pass
        else:
            sqrts.append(np.sqrt(ele))
    return sqrts


## Ejercicio 5: Validación condicional

Escribe un bucle que verifique una lista de nombres. Si encuentra un nombre vacío (cadena vacía), salta esa iteración y continúa con los demás nombres.


In [75]:
names = ["Antonio", "Antonia", "Pepe", "Pepa", "Jose", "", "Mario", "María"]
names_verified = []
for name in names:
    if name == "":
        continue
    else:
        names_verified.append(name)
print(names_verified)

['Antonio', 'Antonia', 'Pepe', 'Pepa', 'Jose', 'Mario', 'María']


## Ejercicio 6: Búsqueda de claves en un diccionario

Escribe un programa que recorra un diccionario y detenga la búsqueda si encuentra una clave específica pasada por el usuario.


In [80]:
cosas = dict(oficina = ["mesa", "silla"], cocina = ["horno", "microondas"], salon = ["sofá", "lámpara"])
key_target = input("Introduzca la clave")
for key in cosas.keys():
    if key == key_target:
        print(cosas[key])
        break
    else:
        continue

## Ejercicio 7: Bucle con múltiples excepciones

Escribe un bucle que procese una lista de operaciones matemáticas, omitiendo las operaciones que intenten dividir por cero.


In [226]:
operaciones = "+,-,*,/".split(sep = ",")
lista_ops = []
op_text = ''
num1 = np.random.randint(-4,10, size = 10)
op = np.random.choice(a = operaciones, size = 10, p = [0.2,0.2,0.2,0.4])
num2 = np.random.choice(a = [-3, -2, -1, 0, 1, 2, 3], p = [0.1, 0.1, 0.1, 0.40, 0.1, 0.1, 0.1], size = 10)

results = []
for i in range(10):
    lista_ops.append(op_text.join([str(num1[i]), op[i], str(num2[i])]))
    if op[i] == '/' and num2[i] == 0:
        continue
    else:   
        results.append(eval(lista_ops[i]))

print(lista_ops)
print(results)


['-1*0', '7-0', '-1*2', '-2/0', '8/0', '8-0', '0*-1', '7*-3', '-1--1', '-4--2']
[0, 7, -2, 8, 0, -21, 0, -2]


## Ejercicio 8: Búsqueda en una lista anidada

Escribe un programa que recorra una lista de listas y detenga la búsqueda cuando encuentre un valor mayor a 50.


In [101]:
lista_anidada = [[1,2,3],[51,1,7,4],[57,4,6]]
encontrado = False
for i in range(len(lista_anidada)):
    for j in range(len(lista_anidada[i])):
        if lista_anidada[i][j] > 50:
            encontrado = True
            print(f"Valor encontrado!: {lista_anidada[i][j]}")
            break
    if encontrado:
        break

Valor encontrado!: 51


## Ejercicio 9: Evaluación de series temporales

Escribe un programa que recorra una lista de datos de series temporales y se detenga si encuentra un valor atípico (mayor a 100).


In [108]:
serie = [x*2 for x in range(1,100)]
for ele in serie:
    if ele > 100:
        print(f"Valor atípico!: {ele}")
        break


Valor atípico!: 102


## Ejercicio 10: Iteración con valores faltantes

Crea un bucle que recorra una lista de datos de ventas y salte los valores faltantes representados por `None`.

In [181]:
a = [x for x in range(20)]
a.append(None)
ventas = np.random.choice(a = a, size = 15)
ventas_limpio = np.array([], dtype = int)
for venta in ventas:
    if venta is None:
        continue
    else:
        ventas_limpio = np.append(ventas_limpio, venta)
print(ventas)
print(ventas_limpio)

[6 None 9 None 9 4 16 14 6 16 1 17 2 None 15]
[ 6  9  9  4 16 14  6 16  1 17  2 15]


## Ejercicio 11: Control de flujo en bucles anidados

Escribe un bucle que recorra la matriz dada y se detenga si se encuentra un número negativo, mostrando su posición.



In [254]:
matrix = np.random.randint(-1,10,size = (4,4))
found = False
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[1]):
        if matrix[i][j] < 0:
            print(f"La posición del negativo {matrix[i][j]} es ({i},{j})")
            found = True
            break
    if found:
        break
print(matrix)

La posición del negativo -1 es (0,3)
[[ 2  4  5 -1]
 [ 7  6  9  7]
 [ 6  6  1  1]
 [ 5  9  7  5]]


## Ejercicio 12: Placeholder para funciones incompletas

Escribe una función que tenga un bloque de control que aún no esté implementado, utilizando `pass` para que no genere errores.

In [276]:
arr = np.random.randint(-1000,1000,size = 10)
def funcion_incompleta(arr, it):
    for i in range(it):
        suma = sum(arr)
        media = suma/len(arr)
        if media < 0:
            pass
        else:
            arr = np.random.randint(-media, media, size = 10)
    return arr, media

funcion_incompleta(arr, 1000)

(array([ 309, -233, -142,  376,  737, -867, -468, -538,  362, -890]), -135.4)